### ISSUE TITLE
Compilation on Linux

### ISSUE THREAD

**Issue by HeliumCore** [AndrewHazelden/dome2rect#2]
Hi, my question is about mpremap : 
I'd like to use dome2rect on a raspberryPi, problem is : mpremap is a windows executable.
I see that you have sources for mpremap, but I have trouble compiling it...

Do you have any Linux binary for mpremap ? Or any help for compilation on Linux...

Thanks, great job on dome2rect

**Comment by AndrewHazelden** [comment]
Hi @HeliumCore. 

I haven't tried compiling mpremap on Linux. When I did try a macOS compile I was unsuccessful at the time.

**Comment by HeliumCore** [comment]
Thanks for the quick answer !

I currently am trying to compile on a RaspberryPi, but i'm struggling with the -m32 command line.
Because RasPi have an ARM processor, it can't compile :(

Anyways, if you can't even compile on UNIX, who am I to try it !
I'll try on a debian VM, will keep you posted if I succeed, it may help other people.
